### PR TITLE
updates runtime/configuration to use CGI.escapeHTML instead of URI.en…

### LINKED ISSUE #72: Ruby 2.7.0+ Support
## Describe the bug

When using the `vsphere-automation-runtime` gem with Ruby 2.7.0+, errors are reported due to `URI.escape` becoming obsolete in `2.7.0`.  The gem appears to still be functioning properly but produces errors when invoked multiple times.

## How to reproduce

This was discovered by using the `kitchen-vcenter` Chef gem which uses `vsphere-automation-runtime`:

`opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/vsphere-automation-runtime-0.4.6/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete`

Ruby version for this is `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c)`

Simple execution:
```
irb(main):001:0> url='http://localhost'
irb(main):002:0> URI.encode(url)
(irb):2: warning: URI.escape is obsolete
=> "http://localhost"
irb(main):003:0> 
```

## Expected behavior

No Ruby deprecation warnings output.

## Versions

**Dev Environment:**

* Ruby: 2.7.1p83
* vSphere Automation SDK: 0.4.6
* OS: MacOS 10.15.5

### PR DESCRIPTION
**Pull request by collinmcneese**
…code

Signed-off-by: Collin McNeese <cmcneese@chef.io>

**What this PR does / why we need it**:
Updates for `2.7.0`+ Ruby to use `CGI.escapeHTML` in `runtime/configuration.rb` instead of deprecated `URI.encode`, preventing current warning errors and eventual fault errors.

**Which issue(s) this PR fixes**:

Fixes #72 

**Special notes for your reviewer**:

Validated that this is working as expected against a vCenter 6.5 instance (all I have access to). 

Existing behavior using spec test as reference:

```
rspec spec/configuration_spec.rb
/path/vsphere-automation-sdk-ruby/runtime/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete

VSphereAutomation::Configuration
  #base_url
/path/vsphere-automation-sdk-ruby/runtime/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete
    should have the default value
/path/vsphere-automation-sdk-ruby/runtime/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete
/path/vsphere-automation-sdk-ruby/runtime/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete
/path/vsphere-automation-sdk-ruby/runtime/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete
/path/vsphere-automation-sdk-ruby/runtime/lib/vsphere-automation-runtime/configuration.rb:174: warning: URI.escape is obsolete
    should remove trailing slashes

Finished in 0.00312 seconds (files took 0.52012 seconds to load)
2 examples, 0 failures
```

After making local modification:

```
rspec spec/configuration_spec.rb

VSphereAutomation::Configuration
  #base_url
    should have the default value
    should remove trailing slashes

Finished in 0.0027 seconds (files took 0.50313 seconds to load)
2 examples, 0 failures
```

Additional snippet from ruby 2.6.3p62:

```
spec spec/configuration_spec.rb

VSphereAutomation::Configuration
  #base_url
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/URI.rb:94: warning: already initialized constant URI::VERSION_CODE
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri.rb:94: warning: previous definition of VERSION_CODE was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/URI.rb:95: warning: already initialized constant URI::VERSION
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri.rb:95: warning: previous definition of VERSION was here
    should have the default value
    should remove trailing slashes

Finished in 0.003 seconds (files took 0.58288 seconds to load)
2 examples, 0 failures
```

### CODE REVIEW

**Comment by collinmcneese** [comment]
@jrgarcia - Does this look okay to you?  I have been using this modified version at a client site against a vCenter 6.5 instance and it is working as expected

**Comment by jrgarcia** [comment]
I haven't had a chance to test it as I've been incredibly busy. I'll test it today and if all is fine, merge it in. From just a quick skim over the PR, it looks great though! Thanks so much for this! 🎉

**Comment by collinmcneese** [comment]
Cool!  I saw you were the only active maintainer so didn't want to come across as pushy =D

Thanks!!

**Comment by jrgarcia** [comment]
Haha, not at all!

**Review by jrgarcia — CHANGES_REQUESTED** [review]
Could you add `require 'cgi'` above the `require 'uri'` line in the `configuration.mustache` template and then the `configuration.rb` output? For me with 2.7.1, it's throwing an error unless I require it first. Other than that, it looks great! 👏

**Comment by collinmcneese** [comment]
> Could you add `require 'cgi'` above the `require 'uri'` line in the `configuration.mustache` template and then the `configuration.rb` output? For me with 2.7.1, it's throwing an error unless I require it first. Other than that, it looks great! 👏

Yep, sorry about that!  The Ruby environment I was running the spec tests from already had 'CGI' loaded in.

**Review by jrgarcia — APPROVED** [review]

**Comment by jrgarcia** [comment]
Thanks for the contribution! 🎉

**Comment by jrgarcia** [comment]
I'll release a version v0.4.7 with this included later today.

**Comment by collinmcneese** [comment]
Awesome, thanks @jrgarcia !!

**Comment by jrgarcia** [comment]
I just released v0.4.7 with your fix included. You should be able to use this without the deprecation warnings in 2.7+ now.

**Pull request merged**
