### PR TITLE
eaygar/vSphereAutomationSDK65Integration

### PR DESCRIPTION
**Pull request by eaygar**
vSphere Automation SDK Integration.

### CODE REVIEW

**Comment by jrgarcia** [comment]
@eaygar I'm not sure what's going on, but I'm assuming you aren't actually meaning to create PRs for this stuff. It seems pretty clear you are customizing this for use on your fork. I'm going to go ahead and close this PR for now.

**Comment by eaygar** [comment]
Oh, I was trying to make changes to our custom fork. Sorry!

**Comment by jrgarcia** [comment]
Not a problem! Enjoy and feel free to submit any feedback you have!

**Comment by eaygar** [comment]
Certainly! So far so good! Btw, I still need to improve the performance on the pulling categories/tags/associations for multiple objects with their names and descriptions. 
Please recall my slack message.

**Pull request closed without merging**
